In [1]:
l = [1, 2, 3]
l

[1, 2, 3]

In [4]:
import numpy as np

a = np.array(l)
a

array([1, 2, 3])

In [5]:
type(l)

list

In [10]:
type(a)

numpy.ndarray

In [9]:
a[2] = 5
a[2]

5

In [11]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
a.dtype

dtype('float64')

In [13]:
a[2] = 4
a

array([0., 0., 4., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
a = np.zeros(10, dtype=np.int64)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
a.dtype

dtype('int64')

In [18]:
a[4] = 9.5
a[4]

9

In [19]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
a.dtype

dtype('float64')

In [21]:
a = np.ones(10) * (-20)
a

array([-20., -20., -20., -20., -20., -20., -20., -20., -20., -20.])

In [22]:
a = np.full(10, 222)
a

array([222, 222, 222, 222, 222, 222, 222, 222, 222, 222])

In [23]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a.dtype

dtype('int64')

In [25]:
2 ** a

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [26]:
1 + a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
2 - a

array([ 2,  1,  0, -1, -2, -3, -4, -5, -6, -7])

In [53]:
a = np.array([[2.,2.,7.], [4., 8., 7.]])
len(a)
a.itemsize

8

In [38]:
a.shape

(2, 3)

In [39]:
type(a)
# a.dtype

numpy.ndarray

In [40]:
a.size

6

In [41]:
a.ndim

2

In [47]:
a.nbytes

48

In [46]:
import sys
sys.getsizeof(a)

176

In [48]:
# list vs. numpy arrays
l1 = [1, 2, 3]
l2 = [10, 12, 13]
l1 + l2

[1, 2, 3, 10, 12, 13]

In [49]:
a1 = np.array(l1)
a2 = np.array(l2)
a1 + a2

array([11, 14, 16])

In [51]:
a1.itemsize

8

In [77]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = np.int64)
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = np.int32)
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = np.int16)
d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, -127], dtype = np.int8)
e = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 256], dtype = np.uint8)

print(a.itemsize, b.itemsize, c.itemsize, d.itemsize, e.itemsize)
print(a.nbytes, b.nbytes, c.nbytes, d.nbytes, e.nbytes)

8 4 2 1 1
80 40 20 10 10


/tmp/ipykernel_4178/2560229294.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -8 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  e = np.array([1, 2, 3, 4, 5, 6, 7, -8, 9, 256], dtype = np.uint8)
/tmp/ipykernel_4178/2560229294.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  e = np.array([1, 2, 3, 4, 5, 6, 7, -8, 9, 256], dtype = np.uint8)


In [73]:
d - 4

array([ -3,  -2,  -1,   0,   1,   2,   3,   4,   5, 123], dtype=int8)

In [59]:
e - 4

array([253, 254, 255,   0,   1,   2,   3,   4,   5,   6], dtype=uint8)

In [79]:
f = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float32)
g = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float64)
h = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float128)

print(f.nbytes, g.nbytes, h.nbytes)

40 80 160


In [81]:
l = np.array([False, True, True])
l.dtype

dtype('bool')

In [84]:
l = np.array([0, 1, 1], dtype = 'bool')
l
l.dtype

dtype('bool')

In [91]:
a1 = np.array([2, 3, 4])
a2 = np.array([1, 6, 5])

In [95]:
a1 + a2
a1 * a2
a1 / a2
a1 ** a2
a1 // a2

array([2, 0, 0])

In [93]:
a1.dtype

dtype('int64')

In [105]:
b = np.array([4,5,6])
a = np.array([1.0,2,3])

In [98]:
a

array([1., 2., 3.])

In [106]:
a.dtype

dtype('float64')

In [103]:
a / b

array([0.25, 0.4 , 0.5 ])

In [107]:
a // b

array([0., 0., 0.])

In [108]:
a = np.array([1,2,3], dtype=np.float64)
a

array([1., 2., 3.])

In [118]:
a = np.array([0,10,20,30,40, 50, 60, 70, 80, 90, 100])
a[2:-1] # **
a[2:8:2]
a[2:8:-1] # **
a[8:2:-1] # **
a[::-1]
a[[4, 7, 9]] # **

array([40, 70, 90])

In [ ]:
# 2D array

In [124]:
A = np.zeros((4, 6))
A.dtype

dtype('float64')

In [123]:
A = np.zeros((4,6), dtype=np.int32)
A

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

In [126]:
A = np.ones((3, 8), dtype = np.uint8)
A

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [133]:
a = np.full((2, 3), 25, dtype=np.float32)
a = np.full((2, 3), 25)
a.dtype

dtype('int64')

In [135]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [136]:
A[1,2]

7

In [137]:
A[2, -2]

11

In [138]:
A[1, 0]

5

In [139]:
A.shape

(3, 4)

In [140]:
A.shape[::-1]

(4, 3)

In [141]:
A.size

12

In [142]:
A.ndim

2

In [143]:
A[0].shape

(4,)

In [148]:
A[0]

array([1, 2, 3, 4])

In [155]:
A[[0]]

array([[1, 2, 3, 4]])

In [150]:
A[[0], :].shape # **

(1, 4)

In [156]:
A[:, 2]

array([ 3,  7, 11])

In [157]:
A[:,[2]] # **

array([[ 3],
       [ 7],
       [11]])

In [158]:
A[:,2].shape

(3,)

In [159]:
A[:, [2]].shape

(3, 1)

In [160]:
A[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [168]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
A[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [169]:
A[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [170]:
A[:, ::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [171]:
r = np.array([0, 1, 0, 2, 2])

In [174]:
A[[1, 1, 2]]

array([[ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [175]:
A[:,0] = 1
A

array([[ 1,  2,  3,  4],
       [ 1,  6,  7,  8],
       [ 1, 10, 11, 12]])

In [176]:
A[:, 2] = 20
A

array([[ 1,  2, 20,  4],
       [ 1,  6, 20,  8],
       [ 1, 10, 20, 12]])

In [183]:
B = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
A

array([[ 1,  2, 20,  4],
       [ 1,  6, 20,  8],
       [ 1, 10, 20, 12]])

In [178]:
A + B

array([[ 2,  3, 21,  5],
       [ 3,  8, 22, 10],
       [ 4, 13, 23, 15]])

In [179]:
A * B

array([[ 1,  2, 20,  4],
       [ 2, 12, 40, 16],
       [ 3, 30, 60, 36]])

In [181]:
np.dot(A,B)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [182]:
A.dot(B)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [184]:
A.dot(B.T)

array([[ 27,  54,  81],
       [ 35,  70, 105],
       [ 43,  86, 129]])

In [186]:
A @ B.T

array([[ 27,  54,  81],
       [ 35,  70, 105],
       [ 43,  86, 129]])

In [188]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
np.random.random((2,3))

array([[0.221104  , 0.86503278, 0.20639943],
       [0.98991834, 0.37998992, 0.64321686]])

In [194]:
np.random.rand(2,3)

array([[0.01880188, 0.49552076, 0.2058465 ],
       [0.96063189, 0.26527359, 0.01328661]])

In [199]:
np.random.randn(2,3)

array([[-0.71949438,  0.09627904, -2.41403961],
       [ 0.97520936, -0.10521739, -0.39279494]])

In [200]:
# reference and copy()

In [201]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
B = A[:, -1]
B

array([ 4,  8, 12])

In [202]:
B[1] = 80
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 80],
       [ 9, 10, 11, 12]])

In [205]:
A_cloned = A.copy()
B = A_cloned[:, -1]
B[-1] = 90
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 80],
       [ 9, 10, 11, 12]])

In [207]:
A = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])

In [208]:
Mask = np.array([[True, False, True, False],
                 [True, True, False, False],
                 [False, False, False, True]])

In [209]:
Mask.dtype

dtype('bool')

In [210]:
A[Mask]

array([ 1,  3,  5,  6, 12])

In [212]:
A[[1, 2], ::-1]

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [213]:
A[~Mask]

array([ 2,  4,  7,  8,  9, 10, 11])

In [214]:
A[Mask] = 222
A

array([[222,   2, 222,   4],
       [222, 222,   7,   8],
       [  9,  10,  11, 222]])

In [215]:
A[~Mask] *= 2
A

array([[222,   4, 222,   8],
       [222, 222,  14,  16],
       [ 18,  20,  22, 222]])

In [216]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [221]:
B = np.zeros_like(A)
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [218]:
B[Mask] = A[Mask]

In [219]:
B

array([[ 1,  0,  3,  0],
       [ 5,  6,  0,  0],
       [ 0,  0,  0, 12]])

In [222]:
A > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [223]:
Mask = A > 2

In [224]:
A[Mask]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [227]:
B = np.zeros_like(A)
Mask = A > 2
B[Mask] = A[Mask]
B

array([[ 0,  0,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [229]:
A > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [231]:
Mask = A < 8
Mask

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [232]:
A[Mask]

array([1, 2, 3, 4, 5, 6, 7])

In [233]:
A[A < 8]

array([1, 2, 3, 4, 5, 6, 7])

In [234]:
A[A < 8] += 100

In [235]:
A

array([[101, 102, 103, 104],
       [105, 106, 107,   8],
       [  9,  10,  11,  12]])

In [236]:
# operations on arrays

In [237]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [238]:
A.sum()

78

In [239]:
A.sum(axis=0)

array([15, 18, 21, 24])

In [240]:
A.sum(axis=1)

array([10, 26, 42])

In [241]:
A.min(axis = 0)

array([1, 2, 3, 4])

In [243]:
A.min(axis=1, keepdims=True)

array([[1],
       [5],
       [9]])

In [244]:
A.prod(axis=0)

array([ 45, 120, 231, 384])

In [245]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [246]:
X = np.array([[1,2],[3,4]])
Y = np.array([[10,20,30],[40,50,60]])
Z = np.array([[7,7],[8,8],[9,9]])

In [252]:
Z

array([[7, 7],
       [8, 8],
       [9, 9]])

In [251]:
X

array([[1, 2],
       [3, 4]])

In [282]:
Y

array([[10, 20, 30],
       [40, 50, 60]])

In [287]:
X

array([[1, 2],
       [3, 4]])

In [289]:
np.hstack((Y,X))

array([[10, 20, 30,  1,  2],
       [40, 50, 60,  3,  4]])

In [268]:
np.concatenate((X,Z), axis=0)

array([[1, 2],
       [3, 4],
       [7, 7],
       [8, 8],
       [9, 9]])

In [292]:
Y

array([[10, 20, 30],
       [40, 50, 60]])

In [265]:
X

array([[1, 2],
       [3, 4]])

In [275]:
Z

array([[7, 7],
       [8, 8],
       [9, 9]])

In [278]:
np.vstack((X,Z))

array([[1, 2],
       [3, 4],
       [7, 7],
       [8, 8],
       [9, 9]])

In [290]:
np.r_[X,Z]

array([[1, 2],
       [3, 4],
       [7, 7],
       [8, 8],
       [9, 9]])

In [291]:
np.c_[X,Y]

array([[ 1,  2, 10, 20, 30],
       [ 3,  4, 40, 50, 60]])

In [295]:
Y.shape

(2, 3)

In [296]:
np.tile(Y,(4,3)).shape

(8, 9)

In [297]:
np.tile(Y,(4,3))

array([[10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60],
       [10, 20, 30, 10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60, 40, 50, 60]])

In [298]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [299]:
A.reshape((4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [300]:
A.reshape((2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [301]:
A.reshape((2, 7))

ValueError: cannot reshape array of size 12 into shape (2,7)

In [302]:
A.size

12

In [303]:
A.reshape((1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [304]:
A.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [308]:
A.reshape((12,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [311]:
b = A.ravel()

In [312]:
b.shape

(12,)

In [313]:
b.reshape((2, 6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [314]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [315]:
b.shape = (2, 6)

In [316]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [320]:
f = A.flatten()
t = A.ravel()
f
# t

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [321]:
f[0] = 400

In [322]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [323]:
t[0] = 400

In [341]:
A


array([[400,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [325]:
# Numpy arrays VS. numpy matrices

In [342]:
A = np.array([[1,2,3], [1,1,1], [-1,-2,-1]])
M = np.matrix([[1,2,3], [1,1,1], [-1,-2,-1]])
M1 = np.array([[1,2,3], [1,1,1], [-1,-2,-1]])

In [327]:
M

matrix([[ 1,  2,  3],
        [ 1,  1,  1],
        [-1, -2, -1]])

In [328]:
M * M

matrix([[ 0, -2,  2],
        [ 1,  1,  3],
        [-2, -2, -4]])

In [335]:
np.multiply(M1,M1)
# np.dot(M1, M1)

array([[1, 4, 9],
       [1, 1, 1],
       [1, 4, 1]])

In [343]:
M=np.mat(A)
M

matrix([[ 1,  2,  3],
        [ 1,  1,  1],
        [-1, -2, -1]])

In [344]:
M.T

matrix([[ 1,  1, -1],
        [ 2,  1, -2],
        [ 3,  1, -1]])

In [345]:
M.I

matrix([[-0.5,  2. ,  0.5],
        [-0. , -1. , -1. ],
        [ 0.5,  0. ,  0.5]])

In [346]:
M.I * M

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [347]:
M * M.I

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [348]:
M.A

array([[ 1,  2,  3],
       [ 1,  1,  1],
       [-1, -2, -1]])

In [349]:
M

matrix([[ 1,  2,  3],
        [ 1,  1,  1],
        [-1, -2, -1]])

In [351]:
C = np.matrix("1 2; 3 4; 5 6")
C

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [352]:
M * C

matrix([[ 22,  28],
        [  9,  12],
        [-12, -16]])

In [353]:
# N-dimensional Array

In [354]:
A = np.zeros((2,4,3))

In [358]:
A

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [359]:
A[:,:,0].shape

(2, 4)

In [360]:
A[:,:,0] = [[1,2,3,4],[5,6,7,8]]
A

array([[[1., 0., 0.],
        [2., 0., 0.],
        [3., 0., 0.],
        [4., 0., 0.]],

       [[5., 0., 0.],
        [6., 0., 0.],
        [7., 0., 0.],
        [8., 0., 0.]]])

In [362]:
A[0,:,:].shape


(4, 3)

In [363]:
A[:,1,:]

array([[2., 0., 0.],
       [6., 0., 0.]])

In [364]:
A[:,1]

array([[2., 0., 0.],
       [6., 0., 0.]])

In [365]:
A[:,[1]]

array([[[2., 0., 0.]],

       [[6., 0., 0.]]])

In [366]:
A[:,1].shape

(2, 3)

In [367]:
A[:,:,0]

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [370]:
A

array([[[1., 0., 0.],
        [2., 0., 0.],
        [3., 0., 0.],
        [4., 0., 0.]],

       [[5., 0., 0.],
        [6., 0., 0.],
        [7., 0., 0.],
        [8., 0., 0.]]])

In [372]:
A[:,2:,0]

array([[3., 4.],
       [7., 8.]])

In [373]:
A.ravel()

array([1., 0., 0., 2., 0., 0., 3., 0., 0., 4., 0., 0., 5., 0., 0., 6., 0.,
       0., 7., 0., 0., 8., 0., 0.])

In [376]:
# Broadcasting

In [380]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.array([1, 0, 2,-2])

In [381]:
A - b

array([[ 0,  2,  1,  6],
       [ 4,  6,  5, 10],
       [ 8, 10,  9, 14]])

In [382]:
c = np.array([1,2,3])

In [384]:
A - c.reshape((3, 1))

array([[0, 1, 2, 3],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [1]:
# ------------------------ warm-up before presentation ------------------------

In [2]:
import numpy as np

In [5]:
a = np.ones(10, dtype=np.int64)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
a.itemsize

8

In [7]:
a.nbytes

80

In [8]:
a.dtype

dtype('int64')

In [9]:
a.size

10

In [11]:
import sys
print(sys.getsizeof(a))
a.nbytes

192


80

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[2:-3]

array([2, 3, 4, 5, 6])

In [9]:
a[8:2:-1]

array([8, 7, 6, 5, 4, 3])

In [10]:
a[[1, 3, 4]] # important, picking multiple elements

array([1, 3, 4])

In [11]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [12]:
A[0,:]

array([1, 2, 3, 4])

In [16]:
A[[0, 1]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
A[:,2]

array([ 3,  7, 11])

In [18]:
A[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [19]:
B = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])

In [20]:
A


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
B

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [22]:
A * B

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36]])

In [24]:
# np.dot(A, B)
A.dot(B)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [25]:
# Mask

In [26]:
A = np.array([[1, 2, 3],
             [2, 3, 5]])
Mask = [[True, False, True],
       [False, False ,False]]

B = np.zeros_like(A)

In [27]:
B[Mask] = A[Mask]
B

array([[1, 0, 3],
       [0, 0, 0]])

In [29]:
# create Mask
A > 3

array([[False, False, False],
       [False, False,  True]])

In [31]:
A[A > 3] *= 100
A

array([[    1,     2,     3],
       [    2,     3, 50000]])

In [32]:
B

array([[1, 0, 3],
       [0, 0, 0]])

In [33]:
A

array([[    1,     2,     3],
       [    2,     3, 50000]])

In [34]:
A.mean(axis=0)

array([1.50000e+00, 2.50000e+00, 2.50015e+04])

In [37]:
A.mean(axis=1).dtype = np.int64
A

array([[    1,     2,     3],
       [    2,     3, 50000]])

In [38]:
# concatenation

In [39]:
X = np.array([[1,2],[3,4]])
Y = np.array([[10,20,30],[40,50,60]])
Z = np.array([[7,7],[8,8],[9,9]])

In [44]:
np.concatenate((X, Z), axis=0)

array([[1, 2],
       [3, 4],
       [7, 7],
       [8, 8],
       [9, 9]])

In [45]:
X

array([[1, 2],
       [3, 4]])

In [46]:
Y

array([[10, 20, 30],
       [40, 50, 60]])

In [48]:
Z

array([[7, 7],
       [8, 8],
       [9, 9]])

In [47]:
np.concatenate((X,Y), axis=1)

array([[ 1,  2, 10, 20, 30],
       [ 3,  4, 40, 50, 60]])

In [49]:
np.vstack((X,Z))

array([[1, 2],
       [3, 4],
       [7, 7],
       [8, 8],
       [9, 9]])